language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
before_install:
    - sudo apt-get install subversion bzr mercurial
    - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
    - git config --global user.email "python-virtualenv@googlegroups.com"
    - git config --global user.name "Pip"
install: pip install nose virtualenv scripttest mock
script: nosetests
branches:
  only:
    - develop
env:
  - PIP_USE_MIRRORS=true
