language: python
python:
  - 2.5
before_install:
    - sudo apt-get install subversion bzr mercurial openssl
    - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
install: pip install nose virtualenv scripttest mock
script: nosetests -s -v tests.test_ssl:Tests_py25.test_install_with_ssl_backport
branches:
  only:
    - ssl_cert_test
    - ssl_cert_test2
env:
  - PIP_USE_MIRRORS=true
