language: python

env:
  - TOXENV=py27
  - TOXENV=py32

install:
  - sudo apt-get install subversion bzr mercurial
  - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
  - git config --global user.email "python-virtualenv@googlegroups.com"
  - git config --global user.name "Pip"
  - pip install tox

script: tox

branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
    - test_xdist

